######
##
# 1) start: docker-compose up -d
# 2) run asr: docker exec kamose asr --help
# 3) check http://localhost:8080 and http://localhost:5000 and http://localhost:5000/shutdown
##
######
version: '2.3'

networks:
  anet:

services:

  # BEGIN: kaldi-model-server
  kamose:
    image: uhhlt/kaldi-model-server:latest
    container_name: kamose
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        PYKALDI_COMMIT: 249963c2cb57d92c0027bb958280dcf8e408462a
        KALDIMODELSERVER_COMMIT: 7ada422a77d924d8f39dad6945406fd31d82bfd2
    volumes:
      - ${PWD}/models:/projects/kaldi-model-server/models
    ports:
      - 5000:5000
    networks:
      - anet
    working_dir: /projects/kaldi-model-server/
    devices:
      - /dev/snd:/dev/snd
  # END: kaldi-model-server
